name: Always Fail on Merge to Main

on:
  pull_request:
    types: [closed]

jobs:
  fail_on_merge_to_main:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Always Fail
        run: exit 1
